### ISSUE TITLE
AD app creation call changed - README needs update

### ISSUE THREAD

**Issue by alf5koe** [DistechControls/CloudRelay#10]
Hi, 

in the README, you suggest to create an AD app with the following call: 
`az ad app create --display-name CloudRelayClient --password S0meHardT0GuessPassw0rd`

The "--password" parameter is no longer supported, see https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration

Now you can have a password created by doing the following...
`az ad app create --display-name CloudRelayClient `
`az ad app credential reset --id <ID of just created app> `

**Comment by usdruscia** [comment]
Hi @alf5koe 
Thanks for bringing this to our attention. We'll update the readme soon.
