### ISSUE TITLE
# Fail to deploy iothub resource using the ARM template

### ISSUE THREAD

**Issue by witlin** [DistechControls/CloudRelay#3]
Tried to follow the steps in the README.md both from a local Windows environment running VS Code with the Azure CLI, and from Azure's web CLI; I got the same error in both instances.
```
PS /home/vms03/git/CloudRelay> az group deployment create `
>>   --handle-extended-json-format `
>>   --name CloudRelayGatewayDeployment `
>>   --resource-group rg-cloudrelaygateway `
>>   --template-file ./deploy/Distech.CloudRelay.ARM/Gateway/Distech.CloudRelay.Gateway.json `
>>   --parameters ./deploy/Distech.CloudRelay.ARM/Gateway/Distech.CloudRelay.Gateway.Parameters.json
Option '--handle-extended-json-format/-j' has been deprecated and will be removed in a future release.
This command is implicitly deprecated because command group 'group deployment' is deprecated and will be removed in a future release. Use 'deployment group' instead.
Please provide string value for 'iotHubName' (? for help): rzzxx-test
Please provide string value for 'storageAccountName' (? for help): cs210032000cec3d56d
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'CloudRelayGatewayDeployment' is not valid according to the validation procedure. The tracking id is 'f001f30f-66cd-4f3b-a889-fdab91d3d76f'. See inner errors for details.
Exception Details:
        Error Code: PreflightValidationCheckFailed
        Message: Preflight validation failed. Please refer to the details for the specific errors.
```

I am able to create the iothub through the UI or CLI, but not with the Distech.CloudRelay.Gateway.json ARM template provided, any help would be most appreciated.

Thanks.

**Comment by usdruscia** [comment]
Hi @witlin,
The deployment command `group deployment` and the option `--handle-extended-json-format/-j` are being deprecated, but still work just fine for now.

Please make sure to run the latest [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) version.
If you still have issues, I would suggest you to go in your Azure subscription, select the resource group **rg-cloudrelaygateway** and click on **Deployments**. You should see your failed deployment with additional details about the error by clicking on the **Related events** link.
